[package]
name = "oauth2-mock"
version = "1.2.0"
edition = "2024"


[dependencies]
axum = {version = "0.8.9", features = ["macros"]}
axum-extra = {version = "0.12.6", features = ["cookie","cookie-signed"]}
tokio = { version = "1.53.1", features = ["net","rt-multi-thread","signal"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
uuid = { version = "1.24.0", features = ["v4", "serde"] }
tower-http = { version = "0.7.0", features = ["timeout"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
chrono = { version = "0.4.45", features = ["serde"] }
base64 = "0.23.1"
rand = "0.10.2"
url = "2.5.8"
clap = { version = "4.6.5", features = ["derive"] }
handlebars = {version = "6.4.3", features = ["rust-embed","dir_source"]}
rust-embed={version ="8.12.0", features = ["include-exclude"]}
cookie = "0.18.1"
config = { version = "0.15.25", default-features = false, features = ["json"] }

[dev-dependencies]
behave ={ version = "0.9.2", features = ["http","url","tokio","json"]}
axum-test = "21.0.0"
rstest = "0.26.1"
yare = "3.0.0"
tempfile = "3.23.0"

[features]
devmode = []
