@url=http://localhost:3000

### 
# Login pages with registered users
GET {{url}}/login?
    &response_type=code
    &client_id=123
    &redirect_uri=http://localhost:8080
    &state=456


###
# Get authorization code by user's login
GET {{url}}/authorize
    ?login=admin
    &response_type=code
    &client_id=123
    &redirect_uri=http://localhost:8080
    &state=456

###
# Get access token by authorization code
POST {{url}}/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&code=96175e5b-d3a8-4add-9f78-6b09838bb1dc
&redirect_uri=http://localhost:8080
&client_id=xxx

###
# Load user info
GET {{url}}/userinfo
Authorization: Bearer 7cf1f752-33a8-4709-a1c4-306821b6efa8

#######################

